version: "3"
services:
  poll:
    build: ./poll
    ports:
      - 5000:80
    restart: on-failure
    environment:
      HOST_REDIS: redis
    networks:
      - poll-tier

  redis:
    image: redis
    ports:
      - 6379
    restart: on-failure
    networks:
      - poll-tier
      - back-tier

  worker:
    build: ./worker
    restart: on-failure
    environment:
      HOST_REDIS: redis
      HOST_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - back-tier

  db:
    image: postgres
    restart: on-failure
    expose:
      - "5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - result-tier
      - back-tier

  result:
    build: ./result
    ports:
      - 5001:80
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - result-tier

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
 db-data:
